/*
 * Wesley Taylor
 * Directory Server RPC
 * 1/17/2017
 *
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "listdir.h"
#include <errno.h>
#include <dirent.h>
#include "stdio.h"
readdir_ret *
readdir_1_svc(nametype *argp, struct svc_req *rqstp)
{
	static readdir_ret  result;
	DIR* dr; // Directory pointer
	struct dirent* drnt;
	namelist *temp;
	/*
	 * insert server code here
	 */
	 // frees the link list
	xdr_free(xdr_readdir_ret, &result);
	//opens directory
	 dr = opendir(*argp) ;
	// Ensures that there is no error preloaded
	// from last operation
	result.err = 0;
	 if(dr == (DIR*)NULL){
		result.err = errno;
		return &result;
	 } 
	 //point to the object
	 temp = &result.readdir_ret_u.list;
	 //prepares for linklist setup
	 while((drnt = readdir(dr)) != NULL)
	{
		//get memory for the struct
		(*temp) = (namenode*)malloc(sizeof(namenode));
		//allocates memory for string
		(*temp)->name = malloc(MAXLEN);
		//copy directory name to string
		strcpy((*temp)->name, drnt->d_name);
		//moves pointer to next.
		temp = &(*temp)->next ;
	}
	//sets last element to null
	(*temp) = NULL;
	//close directory
	closedir(dr);
	return &result;

}
