/*
 * Wesley Taylor
 * directory client RPC
 * 1/17/2017
 * 
 *
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "listdir.h"
#include  "stdio.h"

void
dirprog_1(char *host, char* path)
{
	CLIENT *clnt;
	readdir_ret  *result_1;
	nametype  readdir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	readdir_1_arg = path;
	result_1 = readdir_1(&readdir_1_arg, clnt);
	if (result_1 == (readdir_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		namelist  temp;
	    temp = result_1->readdir_ret_u.list;
		//preparinf to iterate through the link list
		while(temp != NULL){
			printf("%s \n",temp->name);
			temp = temp->next;
		}
	}
	xdr_free(xdr_readdir_ret, &result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dirprog_1 (host, argv[2]);
exit (0);
}
