/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "airport.h"

bool_t
xdr_nametype_air (XDR *xdrs, nametype_air *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AirportNode (XDR *xdrs, AirportNode *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype_air (xdrs, &objp->AirportName))
		 return FALSE;
	 if (!xdr_nametype_air (xdrs, &objp->AirportCode))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (AirportNode), (xdrproc_t) xdr_AirportNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geoCord (XDR *xdrs, geoCord *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_findAirport_ret (XDR *xdrs, findAirport_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->findAirport_ret_u.list, sizeof (AirportNode), (xdrproc_t) xdr_AirportNode))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
