/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"
#include "airport.h"
#include <iostream>
#include "PreFixTree.h"
#include <stdio.h>
#include <unordered_map>
using namespace std;

unordered_map<string, Prefix_Tree*> places;
bool init = false;
//unordered_map<string, double> lol;
//Prefix_Tree places;

void populate_tree(){
	FILE *pFile;
	//unordered_map<string, Prefix_Tree*> places;
	//Prefix_Tree places;
	pFile = fopen("places2k.txt", "r");
	char line[167];
	string state;
	string city;
	unordered_map<string, double> lol;
	while(fgets(line, 167, pFile) != NULL){
		string location(line);
		state = location.substr(0,2);
		city = location.substr(9, 64);
		if(places.find(state) == places.end()){
			Prefix_Tree *tree = new Prefix_Tree();
			places[state] = tree;
		}
		places[state]->insert_word(city, 0.0, 0.0);
		//places.insert_word(state+city, 0.0, 0.0);
		//lol[state+city] = 0.0;
	}
	//for(auto i : places){
	//	delete i.second;
	//}
	fclose(pFile);
}

findPlace_ret *
findplace_1_svc(cityNode *argp, struct svc_req *rqstp)
{
	
	//bool initssdf = false;
	if(!init){
		printf("%s\n", "doiong the init thing");
		populate_tree();
		printf("%s\n", "back from the init");
		init = true;
	}
	static findPlace_ret  result;
	CLIENT *clnt;
	findAirport_ret  *result_1;
	geoCord  findair_1_arg;
	char * host  = "localhost";
	AirportNode ** temp;
	AirportNode_places ** writerPTR;
	/*
	 * insert server code here
	 */
//Thius prints out the core recived the info from the client
	xdr_free((xdrproc_t)xdr_findPlace_ret, (char*)(&result));
	 printf("%s \n", argp->city);
	 printf("%s \n", argp->state);
#ifndef	DEBUG
	clnt = clnt_create (host, AIRPROG, AIR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
//populates the item were sending with information
	double lat = 56.2345;
	double lon = 45.12456;
	findair_1_arg.latitude = lat;
	findair_1_arg.longitude = lon;
//RPC call to airport server
	result_1 = findair_1(&findair_1_arg, clnt);
	if (result_1 == (findAirport_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
//Printing out results from Airport Server
	temp = &result_1->findAirport_ret_u.list;
	printf("%s  \n", (*temp)->AirportName);
	printf("%s  \n", (*temp)->AirportCode);
	printf("%f  \n", (*temp)->latitude);
	printf("%f  \n", (*temp)->longitude);
	printf("%f  \n", (*temp)->distance);
//copy objects im not freeing memory this will happen latter
//when we return the link list
	printf("here");
	printf("%s\n", "and here");
	writerPTR = &result.findPlace_ret_u.list;
	(*writerPTR) = new AirportNode_places();//(AirportNode_places*)malloc(sizeof(AirportNode_places));
	(*writerPTR)->AirportName = new char[MAXLEN];
	(*writerPTR)->AirportCode = new char[MAXLEN];
	
	//bzero((*writerPTR)->AirportName, MAXLEN);
	//bzero((*writerPTR)->AirportCode, MAXLEN);
	strcpy((*writerPTR)->AirportName,(*temp)->AirportName);
	strcpy((*writerPTR)->AirportCode,(*temp)->AirportCode);
	(*writerPTR)->latitude = (*temp)->latitude;
	(*writerPTR)->longitude = (*temp)->longitude;
	(*writerPTR)->distance = (*temp)->distance;
	writerPTR = &(*writerPTR)->next;
	writerPTR = NULL;
	printf("%s\n", "right before return");
	
	return &result;
}

